version: '2'
services:
    safeosmsv2-app:
        image: safeosmsv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://safeosmsv2-postgresql:5432/safeosmsv2
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=safeosmsv2-elasticsearch:9300
        ports:
            - 8088:8088
    safeosmsv2-postgresql:
        extends:
            file: postgresql.yml
            service: safeosmsv2-postgresql
    safeosmsv2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: safeosmsv2-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
