version: '2'
services:
    opencorebankingv1-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/OpenCoreBankingV1/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=OpenCoreBankingV1
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
